spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?stringtype=unspecified
    username: postgres
    password: postgres123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true